### ISSUE TITLE
unable to unmarshal: wappalyzer schema definition file changed

### ISSUE THREAD

**Issue by franciscofreire** [rverton/webanalyze#7]
I installed your tool like described in the README (in Arch Linux) and it keeps giving this error below:
```bash
$ go run cmd/webanalyze/main.go -host https://host/path/ 
2017/08/10 16:24:18 error initializing: json: cannot unmarshal number into Go struct field App.cats of type string
```
Is this normal? After the previous error the execution seems to proceed but hang.
```
2017/08/10 16:24:18 Scanning with 4 workers.
```

**Comment by rverton** [comment]
Thanks for the notice. It looks like the schema of the apps.json file from webanalyze changed again. I will check this.

**Comment by rverton** [comment]
So the problem is that wappalyzer is not very .. strict on their apps.json schema. Have a look at how the usually define their categories, for example:

```
"cats": [
    "20",
    "51"
],
```
And now look at [this](https://github.com/AliasIO/Wappalyzer/blob/ff6ac4726b56cc2686f326fe0967d0405ba8dca3/src/apps.json#L8524):
```
"cats": [
    1
],
```

This fails to unmarshal, because I am expecting a string, and not a number. To fix this you can do this by hand (change 1 to "1"). I will also prepare a PR for the wappalyzer repository.

**Comment by franciscofreire** [comment]
Many thanks you for your quick answer. I made that change in my local apps.json and it works now.
